CREATE TABLE TICKERS
(
  TICKER         VARCHAR(10),
  EXCHANGE		 VARCHAR(10),
  COUNTRY		 VARCHAR(10),
  NAME 			 VARCHAR(100),
  IPOYEAR		 INT,
  SECTOR		 VARCHAR(100),
  INDUSTRY		 VARCHAR(100),
  SUMMARYURL	 VARCHAR(200),
  CREATIONDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (TICKER, EXCHANGE, COUNTRY)
);
CREATE INDEX SECTOR_INDEX ON TICKERS(SECTOR);
CREATE INDEX INDUSTRY_INDEX ON TICKERS(INDUSTRY);

CREATE TABLE TICKER_DATA
(
  TICKER             VARCHAR(10),
  LASTTRADE          FLOAT(15,5),
  TRADEDATE          DATE,
  GAINORLOSS         FLOAT(15,5),
  OPENEDAT           FLOAT(15,5),
  DAYSHIGH           FLOAT(15,5),
  DAYSLOW            FLOAT(15,5),
  TOTALVOLUME        FLOAT(25),
  MARKETCAP          FLOAT(25),
  PREVIOUSCLOSE      FLOAT(15,5),
  PERCENTGAINORLOSS  FLOAT(10,5),
  FIFTYTWOWEEKLOW    FLOAT(15,5),
  FIFTYTWOWEEKHIGH   FLOAT(15,5),
  EPS                FLOAT(15,5),
  PE                 FLOAT(15,5),
  COMPANYNAME        VARCHAR(100),
  CREATIONDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (TICKER, TRADEDATE),
  FOREIGN KEY (TICKER) REFERENCES TICKERS(TICKER)
);	
CREATE INDEX INDEXNAME_TICKER ON TICKER_DATA(TICKER);

CREATE TABLE WATCHLIST
(
  TICKER         VARCHAR(10),
  STOCKEXCHANGE  VARCHAR(50),
  GAIN           FLOAT(5),
  LOSS           FLOAT(5),
  CREATIONDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (TICKER, CREATIONDATE),
  FOREIGN KEY (TICKER) REFERENCES TICKERS(TICKER)
);

CREATE TABLE INDEXES
(
  INDEXNAME		VARCHAR(20),
  COUNTRY		VARCHAR(10),
  NUMBEROFSTOCKS INT,
  URL			VARCHAR(200),
  CREATIONDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(INDEXNAME, COUNTRY)
);
insert into indexes(INDEXNAME, COUNTRY, NUMBEROFSTOCKS, URL, CREATIONDATE) values ("S&P500","USA",500, "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies", sysdate());
insert into indexes(INDEXNAME, COUNTRY, NUMBEROFSTOCKS, URL, CREATIONDATE) values ("DOW30","USA",30, "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average", sysdate());


CREATE TABLE INDEX_DETAIL
(
  TICKER		VARCHAR(10),
  INDEXNAME		VARCHAR(20),
  STATUS		VARCHAR(10),
  CREATIONDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(TICKER, INDEXNAME),
  FOREIGN KEY (TICKER) REFERENCES TICKERS(TICKER),
  FOREIGN KEY (INDEXNAME) REFERENCES INDEXES(INDEXNAME)	
);
CREATE INDEX INDEXNAME_INDEX ON INDEX_DETAIL(INDEXNAME);
CREATE INDEX STATUS_INDEX ON INDEX_DETAIL(STATUS);


CREATE TABLE PROPERTIES
(
  APP_KEY        VARCHAR(30) NOT NULL,
  APP_VALUE		 VARCHAR(500) NOT NULL,
  CREATIONDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIEDDATE   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (APP_KEY)
);
INSERT INTO PROPERTIES (APP_KEY, APP_VALUE) VALUES("IMPORT_BASE_PATH", "/Users/mpadavala/dev/fileimport");