CREATE TABLE STOCK_DETAILS
(
  TICKER             VARCHAR(10),
  LASTTRADE          FLOAT(15,5),
  TRADEDATE          DATE,
  GAINORLOSS         FLOAT(15,5),
  OPENEDAT           FLOAT(15,5),
  DAYSHIGH           FLOAT(15,5),
  DAYSLOW            FLOAT(15,5),
  TOTALVOLUME        FLOAT(25),
  MARKETCAP          FLOAT(25),
  PREVIOUSCLOSE      FLOAT(15,5),
  PERCENTGAINORLOSS  FLOAT(10,5),
  FIFTYTWOWEEKLOW    FLOAT(15,5),
  FIFTYTWOWEEKHIGH   FLOAT(15,5),
  EPS                FLOAT(15,5),
  PE                 FLOAT(15,5),
  COMAPNYNAME        VARCHAR(100),
  CREATIONDATE      DATE
);


CREATE TABLE STOCK_DETAILS_STR
(
  TICKER             VARCHAR(10),
  LASTTRADE          VARCHAR(15),
  TRADEDATE          VARCHAR(15),
  TRADETIME          VARCHAR(15),
  GAINORLOSS         VARCHAR(15),
  OPENEDAT           VARCHAR(15),
  DAYSHIGH           VARCHAR(15),
  DAYSLOW            VARCHAR(15),
  TOTALVOLUME        VARCHAR(25),
  MARKETCAP          VARCHAR(25),
  PREVIOUSCLOSE      VARCHAR(25),
  PERCENTGAINORLOSS  VARCHAR(15),
  FIFTYTWOWEEKRANGE  VARCHAR(50),
  EPS                VARCHAR(15),
  PE                 VARCHAR(15),
  COMAPNYNAME        VARCHAR(100),
  CREATIONDATE       VARCHAR(25)
);


CREATE TABLE STOCK_DETAILS_BKP
(
  TICKER             VARCHAR(10),
  LASTTRADE          VARCHAR(15),
  TRADEDATE          VARCHAR(15),
  GAINORLOSS         VARCHAR(15),
  OPENEDAT           VARCHAR(15),
  DAYSHIGH           VARCHAR(15),
  DAYSLOW            VARCHAR(15),
  TOTALVOLUME        VARCHAR(25),
  MARKETCAP          VARCHAR(25),
  PREVIOUSCLOSE      VARCHAR(25),
  PERCENTGAINORLOSS  VARCHAR(15),
  FIFTYTWOWEEKRANGE  VARCHAR(50),
  EPS                VARCHAR(15),
  PE                 VARCHAR(15),
  COMAPNYNAME        VARCHAR(100),
  CREATIONDATE       VARCHAR(25)
);



CREATE TABLE TICKERS
(
  TICKER         VARCHAR(10),
  COUNTRY		 VARCHAR(10),
  NAME 			 VARCHAR(100),
  IPOYEAR		 INT,
  SECTOR		 VARCHAR(100),
  INDUSTRY		 VARCHAR(100),
  SUMMARYURL	 VARCHAR(200),
  CREATIONDATE   DATE,
  MODIFIEDDATE   DATE,
  PRIMARY KEY (TICKER, COUNTRY)
);
CREATE INDEX SECTOR_INDEX ON TICKERS(SECTOR);
CREATE INDEX INDUSTRY_INDEX ON TICKERS(INDUSTRY);



CREATE TABLE WATCHLIST
(
  TICKER         VARCHAR(10),
  STOCKEXCHANGE  VARCHAR(50),
  GAIN           FLOAT(5),
  LOSS           FLOAT(5),
  CREATIONDATE   VARCHAR(25),
  MODIFIEDDATE   VARCHAR(25),
  PRIMARY KEY (TICKER, CREATIONDATE),
  CONSTRAINT FK_TICKER FOREIGN KEY (TICKER) REFERENCES TICKERS(TICKER)
);



CREATE TABLE TEST_TICKERS
(
  TICKER  VARCHAR(10),
  SECTOR  VARCHAR(1000)
);


CREATE TABLE STOCK_DATA
(
  TICKER             VARCHAR(10),
  LASTTRADE          FLOAT(15,5),
  TRADEDATE          DATE,
  GAINORLOSS         FLOAT(15,5),
  OPENEDAT           FLOAT(15,5),
  DAYSHIGH           FLOAT(15,5),
  DAYSLOW            FLOAT(15,5),
  TOTALVOLUME        FLOAT(25),
  MARKETCAP          FLOAT(25),
  PREVIOUSCLOSE      FLOAT(15,5),
  PERCENTGAINORLOSS  FLOAT(10,5),
  FIFTYTWOWEEKLOW    FLOAT(15,5),
  FIFTYTWOWEEKHIGH   FLOAT(15,5),
  EPS                FLOAT(15,5),
  PE                 FLOAT(15,5),
  COMPANYNAME        VARCHAR(100),
  CREATIONDATE       DATE,
  PRIMARY KEY (TICKER, TRADEDATE)
);	